# title: This will be displayed as the website's name in your browser tab.
title: RemodedUi
baseurl: "/jekyll"
# username: This will displayed on the landing page as your name.
username: RemodedUi

collectios:
  - _links
  - _changelogs
